//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int IdOrderList { get; set; }
        public Nullable<int> IdDetailOrService { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> SumPrice { get; set; }
    
        public virtual DetailOrService DetailOrService { get; set; }
        public virtual Order Order { get; set; }
    }
}
